import type { NextConfig } from "next";
import { createHash } from "crypto";
import { readdirSync, readFileSync } from "fs";
import path from "path";

/* The Pops' files (public/pops, public/dock) are regenerated by tools/ under the same
   names, and images are cached for a year: their URLs carry a hash of the files' contents
   (app/assets.ts), so a changed file is a new URL. */
function assetVersion() {
  const hash = createHash("sha1");
  const walk = (dir: string) => {
    for (const entry of readdirSync(dir, { withFileTypes: true }).sort((x, y) => x.name.localeCompare(y.name))) {
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) walk(full);
      else {
        hash.update(path.relative(process.cwd(), full));
        hash.update(readFileSync(full));
      }
    }
  };
  for (const dir of ["pops", "dock"]) walk(path.join(process.cwd(), "public", dir));
  return hash.digest("hex").slice(0, 10);
}

const nextConfig: NextConfig = {
  env: {
    NEXT_PUBLIC_ASSET_VERSION: assetVersion(),
  },
  // Every `quality` an <Image> asks for (75 is the default); Next.js 16 refuses any other.
  images: { qualities: [75, 78, 80, 90, 95] },
  async headers() {
    return [
      // A year, immutable — in production only: during development the files change under
      // the same names.
      ...(process.env.NODE_ENV === "production"
        ? [
            {
              source: "/:all*(svg|jpg|jpeg|png|webp|gif|ico|woff|woff2|mov|webm)",
              headers: [{ key: "Cache-Control", value: "public, max-age=31536000, immutable" }],
            },
          ]
        : []),
      // The CDN keeps the page five minutes (production only, like the long cache above).
      ...(process.env.NODE_ENV === "production"
        ? [
            {
              source: "/",
              headers: [{ key: "Cache-Control", value: "public, s-maxage=300, stale-while-revalidate=86400" }],
            },
          ]
        : []),
      {
        source: "/:path*",
        headers: [
          { key: "X-Content-Type-Options", value: "nosniff" },
          { key: "Referrer-Policy", value: "strict-origin-when-cross-origin" },
          { key: "X-Frame-Options", value: "SAMEORIGIN" },
          {
            key: "Permissions-Policy",
            value: "camera=(), microphone=(), geolocation=(), interest-cohort=()",
          },
          {
            key: "Strict-Transport-Security",
            value: "max-age=31536000; includeSubDomains",
          },
        ],
      },
    ];
  },
  async redirects() {
    return [
      {
        // The Connected-podcast promo landing page is retired. Send it home.
        // Temporary (307) on purpose: the URL can be revived for a future
        // promo without browsers having permanently cached the redirect.
        source: "/connected",
        destination: "/",
        permanent: false,
      },
    ];
  },
};

export default nextConfig;
